# Generated by Django 3.0.7 on 2020-06-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_useraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
