# Generated by Django 3.0.7 on 2020-06-26 08:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_userdefaultaddresses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDefaultAddresses',
            new_name='UserDefaultAddress',
        ),
    ]
