# Generated by Django 3.0.7 on 2020-06-16 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200616_1321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
