# Generated by Django 3.0.7 on 2020-06-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_variationmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
